apiVersion: argoproj.io/v1aplha1
kind: Application
metadata:
  name: argo-argo-yaml
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/BumbaruFlaviusGabriel/argogolang.git
    targetRevision: main
    path: argo
  destination:
    server: https://kubernetes.default.svc
    namespace: argogolangyaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      