apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-deployment
  namespace: newnamespace
  labels:
    app: golang
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - name: golang
        image: princeatoss/golanggraph:1.1
        resources:
          limits:
            memory: "250Mi"
            cpu: "250m"
          requests:
            memory: "150Mi"
            cpu: "100m"
        ports:
          - containerPort: 8081
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                key: url
                name: db-secret
        